[package]
name = "layer-presentation"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
serde.workspace = true
