version: "3.8"

services:
  db:
    container_name: study-rust-be-db
    image: postgres:18.0-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_dev
    ports:
      - "5432:5432"
    volumes:
      - ./init/db:/docker-entrypoint-initdb.d:ro
      - ./init/db/postgres.conf:/etc/postgresql/postgresql.conf:ro
    env_file:
      - .env.db
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U postgres",
      ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    container_name: study-rust-be
    build:
      context: .
      dockerfile: ./docker/backend-dev/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/tmp/backend
